"""workspace and interviewer notes

Revision ID: 01931b39ba4c
Revises: 9ccdc1bfb9bf
Create Date: 2026-09-27 13:14:59.209977

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01931b39ba4c"
down_revision: str | Sequence[str] | None = "9ccdc1bfb9bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rounds", sa.Column("final_whiteboard", sa.Text(), nullable=True))
    op.add_column("rounds", sa.Column("agent_notes", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rounds", "agent_notes")
    op.drop_column("rounds", "final_whiteboard")
    # ### end Alembic commands ###
