"""company research cache and interviewer voice

Revision ID: 7dff1bd05e8c
Revises: 01931b39ba4c
Create Date: 2026-09-27 14:59:10.482797

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7dff1bd05e8c"
down_revision: str | Sequence[str] | None = "01931b39ba4c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_research",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=300), nullable=False),
        sa.Column("company", sa.String(length=200), nullable=False),
        sa.Column("role_family", sa.String(length=50), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_company_research_key"), "company_research", ["key"], unique=True)
    op.add_column(
        "rounds",
        sa.Column("voice", sa.String(length=10), nullable=False, server_default="female"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rounds", "voice")
    op.drop_index(op.f("ix_company_research_key"), table_name="company_research")
    op.drop_table("company_research")
    # ### end Alembic commands ###
