"""interview language

Revision ID: 8485c6e82591
Revises: 7dff1bd05e8c
Create Date: 2026-09-30 12:53:12.234978

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8485c6e82591"
down_revision: str | Sequence[str] | None = "7dff1bd05e8c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rounds",
        sa.Column("language", sa.String(length=10), server_default="english", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rounds", "language")
    # ### end Alembic commands ###
